// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../myproject/bar.js', ['myproject.bar'], ['goog.string'], {});
goog.addDependency('../../../../myproject/foo.js', ['myproject.foo'], ['goog.array', 'goog.dom', 'myproject.bar'], {});
goog.addDependency('../../../../myproject/mymodule.js', ['myproject.mymodule'], ['myproject.mymodule2'], {});
goog.addDependency('../../../../myproject/mymodule2.js', ['myproject.mymodule2'], [], {});
goog.addDependency('../../../../myproject/start.js', ['myproject.start'], ['goog.dom', 'goog.dom.TagName', 'myproject.mymodule'], {});
